setwd("/Users/galst/Documents/School/R/Titanic")
train <- read.csv("train.csv", stringsAsFactors=FALSE)
test <- read.csv("test.csv", stringsAsFactors=FALSE)
library(rpart)
fit <- rpart(Survived ~ Pclass + Sex + Age + Parch + Fare + Embarked, data=train, method="class")
install.packages('rattle')
install.packages('rpart.plot')
install.packages('RColorBrewer')
library(rattle)
library(rpart.plot)
library(RColorBrewer)
fancyRpartPlot(fit)
Prediction <- predict(fit, test, type = "class")
submit <- data.frame(PassengerId = test$PassengerId, Survived = Prediction)
write.csv(submit, file = "firstTry.csv", row.names = FALSE)
